name: CD

on: [push]

jobs:
  deploy:
    name: Deployment
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run
      env:
        IP: 13.124.238.160
      run: |
        export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
        export AWS_SECRET_ACCESS_KEY=$(( secretes.AWS_SECRET_ACCESS_KEY }}
      aws s3 cp index.html s3://workshop-practice/$IP/ --acl public-read
